### PR TITLE
Closes #15, Closes #31: CSV Parsing + Admin View UI Update

### LINKED ISSUE #15: CSV Parsing Back-end
**This issue depends on #14.**

Take the front-end request, parse the CSV file with a library of your choice and insert into the DB.

CSV Library: https://docs.python.org/2/library/csv.html (Probably the best option)

### LINKED ISSUE #31: Admin View UI Update
1. Add anything reasonable to be searchable
2. Remove anything mostly unique from the filter

### PR DESCRIPTION
**Pull request by leesw98**
Closes #15, Closes #31

Minor changes in admin.py
Minor formatting changes in index.html
Implemented CSV parsing based on `10b Dummy.csv` file

Also **tabs** > spaces.

### CODE REVIEW

**Comment by leesw98** [comment]
It shows up for me right now. Did you remember to `git pull`?

**Comment by Csignore** [comment]
Everything works fine in my laptop, we can merge it; btw, I worked on the issue of adding all the search fields, based on this branch; it is fixed and I push it on my branch, if we wanna merge, we can merge my branch directly

**Comment by gauravnv** [comment]
I did it in another branch on local. Sorry about that. It's working!

**Comment by leesw98** [comment]
@Csignore Make another pull request closing respective issue.

**Pull request merged**
