### PR TITLE
Progress Bar + Async handling

### LINKED ISSUE #47: Asynchronous view-handling while parsing
This will use celery and rabbitMQ to perform asynchronous database parsing while returning a view.

### PR DESCRIPTION
**Pull request by omar2535**
Pip install all the missing modules. 

I used django-celery and rabbitMQ(requires manual installation). 

Run worker separately using "celery -A reboot worker -l info --pool=solo"
Then in another terminal, run "python manage.py runserver"

closes #47

### CODE REVIEW

**Comment by leesw98** [comment]
@omar2535 Can you check if it works for you still? After I added/configured celery.py, it seems to be working for me now.

**Comment by omar2535** [comment]
@leesw98 Works for me 👍

**Comment by omar2535** [comment]
@leesw98  Check if it still works. I also removed the celery panel off the admin page. Also, see if you like the progress bar.

**Comment by leesw98** [comment]
The progress bar doesn't seem to be working.

I see the design change but the progress is going from 0% to 100% instantly and the worker is still running in the background. I like that you took off celery panel. It probably would have just confused reboot tbh.

**Comment by omar2535** [comment]
@leesw98 third try has to be the charm

**Comment by leesw98** [comment]
Also do a fix on the header. I just saw it :/

**Pull request merged**
